config/routes.rb
Rails.application.routes.draw do
  resources :departamentos
  resources :produtos, only:[:new, :create, :destroy]
  post "/produtos/busca" => "produtos#busca", as: :busca_produto
  root "produtos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/departamento.rb
class Departamento < ApplicationRecord
    
end

app/models/produto.rb
class Produto < ApplicationRecord

    belongs_to :departamento
    validates :quantidade, presence: true
    validates :nome, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: %i[ show edit update destroy ]

  # GET /departamentos or /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1 or /departamentos/1.json
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos or /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to departamento_url(@departamento), notice: "Departamento was successfully created." }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1 or /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to departamento_url(@departamento), notice: "Departamento was successfully updated." }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1 or /departamentos/1.json
  def destroy
    @departamento.destroy

    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: "Departamento was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def departamento_params
      params.require(:departamento).permit(:nome)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

    def index 
       @produtos_por_nome = Produto.order :nome
    end

    def create
        
        valores = params.require(:produto).permit :nome, :preco, :descricao, :quantidade, :departamento_id
        @produto = Produto.new valores
        if @produto.save
            flash[:notice] = "Produto salvo com sucesso"
       
            redirect_to root_url
        else 
            render :new
        end
    end
    def new 
        @produto = Produto.new
        @departamentos = Departamento.all
    end

    def destroy
        redirect_to root_url
        id = params[:id]
        Produto.destroy id
    end 
    def busca 
    
        @nome_a_buscar = params[:nome]
        @produtos  = Produto.where "nome like ?", "%#{@nome_a_buscar}%"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/departamentos/_departamento.html.erb
<div id="<%= dom_id departamento %>">
  <p>
    <strong>Nome:</strong>
    <%= departamento.nome %>
  </p>

</div>

app/views/departamentos/_form.html.erb
<%= form_with(model: departamento) do |form| %>
  <% if departamento.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
        <% departamento.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing departamento</h1>

<%= render "form", departamento: @departamento %>

<br>

<div>
  <%= link_to "Show this departamento", @departamento %> |
  <%= link_to "Back to departamentos", departamentos_path %>
</div>

app/views/departamentos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Departamentos</h1>

<div id="departamentos">
  <% @departamentos.each do |departamento| %>
    <%= render departamento %>
    <p>
      <%= link_to "Show this departamento", departamento %>
    </p>
  <% end %>
</div>

<%= link_to "New departamento", new_departamento_path %>

app/views/departamentos/new.html.erb
<h1>New departamento</h1>

<%= render "form", departamento: @departamento %>

<br>

<div>
  <%= link_to "Back to departamentos", departamentos_path %>
</div>

app/views/departamentos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @departamento %>

<div>
  <%= link_to "Edit this departamento", edit_departamento_path(@departamento) %> |
  <%= link_to "Back to departamentos", departamentos_path %>

  <%= button_to "Destroy this departamento", @departamento, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= nav_bar brand:"Camisetas Leto", method: :get, brand_link: root_url do %>
      <%= form_tag busca_produto_path, class:"navbar-form navbar-right" do %>
        <div class="form-group">
          <%= text_field_tag :nome, @nome_a_buscar,  class: "form-control" %>
          <%= button_to "Buscar", nil, class: "btn btn-default"  %>
        </div>
      <% end %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/produtos/_produto.html.erb
<tr>
    <td><%= produto.departamento_id %></td>
    <td><%= produto.nome %></td>
    <td><%= produto.descricao %></td>

    <td><%= produto.preco %></td>
    <td>
        <%= 
            button_to "Remover", 
            produto, method: :delete, 
            class: "btn btn-danger", 
            data:{ confirm:"Tem certeza que deseja remover #{produto.nome}"}
        %>
    </td>
</tr>

app/views/produtos/busca.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table class="table">
        <thead>
            <tr>
                <th>Departamento</th>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Preço</th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            <%= render @produtos %>
       
        </tbody>
    </table>
    <%= link_to "Criar novo produto", new_produto_path %>
</body>
</html>

app/views/produtos/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <% if flash[:notice] %>
        <div class="alert alert-success" role="alert">
            <%= flash[:notice] %>
        </div>
    <% end %>
    <table class="table">
        <thead>
            <tr>
                <th>Departamento</th>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Preço</th>
                # <th>Quantidade</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            <%= render @produtos_por_nome %>
           
        </tbody>
    </table>
    <%= link_to "Criar novo produto", new_produto_path %>
</body>
</html>

app/views/produtos/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Novo Produto</title>
</head>
<body>
    <% @produto.errors.full_messages.each do |message| %>
        <div class="alert alert-danger" role="alert">
            <%= message %>
        </div>
    <% end %>

    <%= form_for @produto do |f| %>
        <div class="form-group">
            <%= f.label :nome %>
            <%= f.text_field :nome, class: "form-control"  %>
        </div>
        <div class="form-group">
            <%= f.label :descricao %>
            <%= f.text_area :descricao, class: "form-control", rows: 4 %>
        </div>
        <div class="form-group">
            <%= f.label :quantidade %>
            <%= f.number_field :quantidade, step:1, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :preco %>
            <%= f.number_field :preco, class: "form-control" %>
        </div>
         <div class="form-group">
            <%= f.label :departamento %>
            <%= f.collection_select :departamento_id, @departamentos, :id, :nome, {}, class: "form-control" %>
        </div>
        <%= f.submit "Criar produto", class: "btn btn-default"%>

    <% end %>

    </form>
</body>
</html>